# TOML Document for Terra-Validator Exporter(Pometheus & Grafana)

title = "TOML Document"

[Servers]
	[Servers.addr]
	rpc = "15.164.30.221:26657"
	rest = "15.164.30.221:1317"

[Validator]
operatorAddr = "terravaloper1tusfpgvjrplqg2fm7wacy4slzjmnzswcfufuvp"

[Options]
listenPort = "26661"
