{
 "title": "Validator Info",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "###### Terra_Network ######", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Terra_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{chainId}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_blockHeight{instance=\"localhost:26661\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_proposerWalletAccountNumber{instance=\"localhost:26661\"}",
     "legendFormat": "proposerWalletAccountNumber"
    }
   ]
  },
  {
   "title": "[ Current Block Time ]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "Terra_currentBlockTime{instance=\"localhost:26661\"}\t",
     "legendFormat": "currentBlockTime"
    }
   ]
  },
  {
   "title": "[ Token Info ]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(Terra_notBondedTokens{instance=\"localhost:26661\"}+Terra_bondedTokens{instance=\"localhost:26661\"})",
     "legendFormat": "totalTokens"
    },
    {
     "expr": "round(Terra_notBondedTokens{instance=\"localhost:26661\"})",
     "legendFormat": "notBondedTokens"
    },
    {
     "expr": "round(Terra_bondedTokens{instance=\"localhost:26661\"})",
     "legendFormat": "bondedTokens"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_bondedRate{instance=\"localhost:26661\"}*100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_validatorCount{instance=\"localhost:26661\"}\t"
    }
   ]
  },
  {
   "title": "[ Block Precommit Rate(%) ]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Terra_precommitRate{instance=\"localhost:26661\"}",
     "legendFormat": "commitStatus"
    }
   ]
  },
  {
   "title": "[ Current Block Time ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_currentBlockTime{instance=\"localhost:26661\"}\t",
     "legendFormat": "currentBlockTime"
    }
   ]
  },
  {
   "title": "[ Average Block Time ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "Terra_currentBlockTime{instance=\"localhost:26661\"}\t",
     "legendFormat": "currentBlockTime"
    }
   ]
  },
  { "title": "###### Terra_Validator ######", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "[ Operator-Address ]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Terra_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{operatorAddress}}"
    }
   ]
  },
  {
   "title": "[ Account-Address ]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Terra_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{accountAddress}}"
    }
   ]
  },
  {
   "title": "[ Account-Address ]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 14 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Terra_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{accountAddress}}"
    }
   ]
  },
  {
   "title": "[ Consensus-PublicKey ]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Terra_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{validatorPubKey}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "Terra_labels{instance=\"localhost:26661\"}\t",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 16 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_votingPower{instance=\"localhost:26661\"}",
     "legendFormat": "votingPower"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 16 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_delegationRatio{instance=\"localhost:26661\"}*100",
     "legendFormat": "delegationRatio"
    }
   ]
  },
  {
   "title": "[ Commission-Rate ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 16 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_commissionRate{instance=\"localhost:26661\"}*100",
     "legendFormat": "commissionRate"
    }
   ]
  },
  {
   "title": "[ Proposing Priority ]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "Terra_proposerPriority{instance=\"localhost:26661\"}",
     "legendFormat": "jailStatus"
    }
   ]
  },
  {
   "title": "[ Jail Status ]",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "targets": [
    {
     "expr": "Terra_jailed{instance=\"localhost:26661\"}\t",
     "legendFormat": "jailStatus"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 18 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_selfDelegationAmount{instance=\"localhost:26661\"}\t",
     "legendFormat": "selfDelegationAmount"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 18 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_delegatorCount{instance=\"localhost:26661\"}",
     "legendFormat": "delegatorCount"
    }
   ]
  },
  {
   "title": "[ Commission-MaxChangeRate ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 19 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_commissionMaxChangeRate{instance=\"localhost:26661\"}*100",
     "legendFormat": "commissionMaxChangeRate"
    }
   ]
  },
  {
   "title": "[ Self Delegation Amount(Luna) History ]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Terra_selfDelegationAmount{instance=\"localhost:26661\"}",
     "legendFormat": "selfDelegationAmount"
    }
   ]
  },
  {
   "title": "[ Proposing Status ]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Terra_proposingStatus{instance=\"localhost:26661\"}",
     "legendFormat": "proposingStatus"
    }
   ]
  },
  {
   "title": "[ Commission-MaxRate ]",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 22 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "Terra_commissionMaxRate{instance=\"localhost:26661\"}*100",
     "legendFormat": "commissionMaxRate"
    }
   ]
  },
  {
   "title": "[ Precommit Status(Uptime) ]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Terra_validatorCommitStatus{instance=\"localhost:26661\"}",
     "legendFormat": "validatorCommitStatus"
    }
   ]
  },
  {
   "title": "[ Current Balances ]",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "Terra_balances_uluna{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "balaces_uluna"
    },
    {
     "expr": "Terra_balances_ukrw{instance=\"localhost:26661\"}",
     "legendFormat": "balances_ukrw"
    },
    {
     "expr": "Terra_balances_uusd{instance=\"localhost:26661\"}",
     "legendFormat": "balances_uusd"
    },
    {
     "expr": "Terra_balances_usdr{instance=\"localhost:26661\"}",
     "legendFormat": "balances_usdr"
    }
   ]
  },
  {
   "title": "[ Balances History ]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Terra_balances_uluna{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "balances_uluna"
    },
    {
     "expr": "Terra_balances_ukrw{instance=\"localhost:26661\"}",
     "legendFormat": "balances_ukrw"
    },
    {
     "expr": "Terra_balances_uusd{instance=\"localhost:26661\"}",
     "legendFormat": "balances_uusd"
    },
    {
     "expr": "Terra_balances_usdr{instance=\"localhost:26661\"}",
     "legendFormat": "balances_usdr"
    }
   ]
  },
  {
   "title": "[ Balances DataTable ]",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 29 },
   "targets": [
    {
     "expr": "Terra_balances_uluna{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "balances_uluna"
    },
    {
     "expr": "Terra_balances_ukrw{instance=\"localhost:26661\"}",
     "legendFormat": "balances_ukrw"
    },
    {
     "expr": "Terra_balances_uusd{instance=\"localhost:26661\"}",
     "legendFormat": "balances_uusd"
    },
    {
     "expr": "Terra_balances_usdr{instance=\"localhost:26661\"}",
     "legendFormat": "balances_usdr"
    }
   ]
  },
  {
   "title": "[ Current Commission ]",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "Terra_commission_uluna{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "commission_uluna"
    },
    {
     "expr": "Terra_commission_ukrw{instance=\"localhost:26661\"}",
     "legendFormat": "commission_ukrw"
    },
    {
     "expr": "Terra_commission_uusd{instance=\"localhost:26661\"}",
     "legendFormat": "commission_uusd"
    },
    {
     "expr": "Terra_commission_usdr{instance=\"localhost:26661\"}",
     "legendFormat": "commission_usdr"
    }
   ]
  },
  {
   "title": "[ Commission History ]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Terra_commission_uluna{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "commission_uluna"
    },
    {
     "expr": "Terra_commission_ukrw{instance=\"localhost:26661\"}",
     "legendFormat": "commissions_ukrw"
    },
    {
     "expr": "Terra_commission_uusd{instance=\"localhost:26661\"}",
     "legendFormat": "commission_uusd"
    },
    {
     "expr": "Terra_commission_usdr{instance=\"localhost:26661\"}",
     "legendFormat": "commission_usdr"
    }
   ]
  },
  {
   "title": "[ Commission DataTable ]",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 35 },
   "targets": [
    {
     "expr": "Terra_commission_uluna{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "commission_uluna"
    },
    {
     "expr": "Terra_commission_ukrw{instance=\"localhost:26661\"}",
     "legendFormat": "commission_ukrw"
    },
    {
     "expr": "Terra_commission_uusd{instance=\"localhost:26661\"}",
     "legendFormat": "commission_uusd"
    },
    {
     "expr": "Terra_commission_usdr{instance=\"localhost:26661\"}",
     "legendFormat": "commission_usdr"
    }
   ]
  },
  {
   "title": "[ Current Rewards ]",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "Terra_rewards_uluna{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "rewards_uluna"
    },
    {
     "expr": "Terra_rewards_ukrw{instance=\"localhost:26661\"}",
     "legendFormat": "rewards_ukrw"
    },
    {
     "expr": "Terra_rewards_uusd{instance=\"localhost:26661\"}",
     "legendFormat": "rewards_uusd"
    },
    {
     "expr": "Terra_rewards_usdr{instance=\"localhost:26661\"}",
     "legendFormat": "rewards_usdr"
    }
   ]
  },
  {
   "title": "[ Rewards History ]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Terra_rewards_uluna{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "rewards_uluna"
    },
    {
     "expr": "Terra_rewards_ukrw{instance=\"1localhost:26661\"}",
     "legendFormat": "rewards_ukrw"
    },
    {
     "expr": "Terra_rewards_uusd{instance=\"localhost:26661\"}",
     "legendFormat": "rewards_uusd"
    },
    {
     "expr": "Terra_rewards_usdr{instance=\"localhost:26661\"}",
     "legendFormat": "rewards_usdr"
    }
   ]
  },
  {
   "title": "[ Rewards DataTable ]",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 40 },
   "targets": [
    {
     "expr": "Terra_rewards_uluna{instance=\"localhost:26661\"}\n\n",
     "legendFormat": "rewards_uluna"
    },
    {
     "expr": "Terra_rewards_ukrw{instance=\"localhost:26661\"}",
     "legendFormat": "rewards_ukrw"
    },
    {
     "expr": "Terra_rewards_uusd{instance=\"localhost:26661\"}",
     "legendFormat": "rewards_uusd"
    },
    {
     "expr": "Terra_rewards_usdr{instance=\"localhost:26661\"}",
     "legendFormat": "rewards_usdr"
    }
   ]
  }
 ]
}